import { Badge } from "@/components/Badge";
import { Box } from "@/components/Box";
import { Card } from "@/components/Card";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box
          display="flex"
          flexDirection="column"
          backgroundColor="primary"
          padding="2"
        >
          <h1 style={{ textAlign: "center" }}>Title</h1>
          <Card>
            <span>This is Card</span>
            <Badge color="primary" variant="outline">
              Primary
            </Badge>
            <Badge color="secondary" variant="solid">
              Primary
            </Badge>
          </Card>
        </Box>
      </main>
    </>
  );
}
